import type { Metadata } from 'next'
import {checkUser } from "@/lib/checkUser"
import { Geist, Geist_Mono } from 'next/font/google'
import { Toaster } from "@/components/ui/sonner"
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const user = await checkUser()

  return (
  
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
         <main className='w-screen h-screen flex flex-col items-center justify-center'>

           {children}
          <Toaster />
         </main>
         
        </body>
      </html>
 
  )
}